- name: "Enable dnsmasq over firewalld"
  firewalld: 
    service: dns
    permanent: true
    state: enabled

- name: Copy dnsmasq config
  template:
    src=ltsp.conf.j2
    dest=/etc/dnsmasq.d/ltsp.conf
  with_items: 
    - { ipaddress: '{{ ipaddress }}' }  
  notify:
    - restart dnsmasq