- name: "Include FOG Variables"
  include_vars: "fog-RedHat-vars.yml"

- name: "Download FOG 1.4.4 from Github to /root/fogproject"
  unarchive:
    src: https://github.com/FOGProject/fogproject/releases/download/1.4.4/fog_1.4.4.tar.gz
    dest: /root/
    remote_src: yes

- name: "Rename FOG_1.4.4 folder to fogproject"
  shell:
    mv fog_1.4.4 fogproject
  # STEP 1, GET FOGPROJECT ONTO REMOTE SYSTEM
#- name: Extract fogproject.zip into /root/fogproject
#  unarchive:
#    src: ../templates/fogproject.zip
#    dest: /root/

- name: Generate FOG password to use
  shell: openssl rand -base64 32
  register: openssl_password

- set_fact:
    password: "{{ openssl_password.stdout }}"

- name: Create FOG User
  user: 
    name: '{{ username }}'
    shell: /bin/bash 
    createhome: yes  
    password: '{{ item.password | password_hash("sha512") }}'
    update_password: on_create
  with_items: 
    - { password: '{{ password }}' }  

# Configure PHP INI with new file upload sizes
- name: "Replace POST Max Size (PHPINI)"
  replace:
    path: '{{ phpini }}'
    regexp: 'post_max_size = 8M'
    replace: 'post_max_size = 3000M'
  
- name: "Replace Max File Size (PHPINI)"
  replace:
    path: '{{ phpini }}'
    regexp: 'upload_max_filesize = 2M'
    replace: 'upload_max_filesize = 3000M'

- name: "Replace Max Input Vars (PHPINI)"
  replace:
    path: '{{ phpini }}'
    regexp: 'max_input_vars = 1000'
    replace: 'max_input_vars = 250000'


# BEGIN configureHttpd
# Create FOG Web Folder
- name: Create FOG Web Folder
  file:
    path: /var/www/html/fog
    state: directory
    owner: apache
    group: apache
    mode: 0755
  register: fogwebfoldercreated

# Create Symlink in webdir
- name: "Create Symlink for FOG Webdir"
  file:
    src: /var/www/html/fog
    dest: /var/www/fog
    owner: root
    group: root
    state: link
    force: yes
  when: fogwebfoldercreated.changed

- name: "Copy files to webdir"
  shell: "cp -Rf /root/fogproject/{{ webdirsrc }}. {{ webdirdest }}"

- name: "Configure config.class.php" # I'll be amazed if this works
  template:
    src: httpd/config.class.php.j2
    dest: '{{ webdirdest }}lib/fog/config.class.php'
  with_items: 
    - { snmysqlhost: '{{ snmysqlhost }}', snmysqluser: '{{ snmysqluser }}', snmysqlpass: '{{ snmysqlpass }}', interface: '{{ interface }}', ipaddress: '{{ ipaddress }}', username: '{{ username }}', password: '{{ password }}', webdirdest: '{{ webdirdest }}', storageLocation: '{{ storageLocation }}', storageLocationCapture: '{{ storageLocationCapture }}', webroot: '{{ webroot }}', snapindir: '{{ snapindir }}' }   

# BEGIN downloadfiles

- name: "Downloading init.xz, kernels, and the fog client"
  get_url:
    url: https://fogproject.org/inits/init.xz 
    dest: '{{ webdirdest }}service/ipxe/init.xz'

- name: "Downloading init_32.xz"
  get_url:
    url: https://fogproject.org/inits/init_32.xz
    dest: '{{ webdirdest }}service/ipxe/init_32.xz' 
    
- name: "Downloading bzImage"
  get_url:
    url: https://fogproject.org/kernels/bzImage
    dest: '{{ webdirdest }}service/ipxe/bzImage'

- name: "Downloading bzImage32"
  get_url:
    url: https://fogproject.org/kernels/bzImage32
    dest: '{{ webdirdest }}service/ipxe/bzImage32'

- name: "Download FOG Service (MSI)"
  get_url:
    url: '{{ clienturl }}'
    dest: '{{ webdirdest }}client/FOGService.msi'

- name: "Download FOG Smart Installer"
  get_url:
    url: '{{ siurl }}'
    dest: '{{ webdirdest }}client/SmartInstaller.exe'

# END downloadfiles

- name: "Enable httpd"
  systemd:
    name: httpd
    enabled: yes
    state: started

- name: "Enable php-fpm"
  systemd:
    name: php-fpm 
    enabled: yes
    state: started

# BEGIN createSSLCA

- name: "Create snapin SSL CA Directory"
  file:
    path: '{{ sslpath }}CA'
    state: directory
    owner: fog
    group: apache
    mode: 0777 # This seems wrong from the script

- name: "Generate SSL CA Key for Snapin Directory (Creating SSL CA)"
  shell:
    openssl genrsa -out '{{ vars["sslpath"] + "CA/.fogCA.key" }}' 4096

  #openssl_privatekey:
  #  path: '{{ vars["sslpath"] + "CA/.fogCA.key" }}'
  #  force: yes







- name: "Generate SSL PEM Key for Snapin Directory"
  shell: |
    openssl req -x509 -new -sha512 -nodes -key '{{ vars["sslpath"] + "CA/.fogCA.key" }}' -days 3650 -out '{{ vars["sslpath"] + "CA/.fogCA.pem" }}' << EOF
    . 
    . 
    . 
    . 
    . 
    FOG Server CA 
    . 
    EOF
  #openssl_publickey:
  #  path: '{{ vars["sslpath"] + "CA/.fogCA.pem" }}'
  #  privatekey_path: '{{ vars["sslpath"] + "CA/.fogCA.key" }}'
  #  force: True


- name: "Creating SSL Private Key Directory (Creating SSL Private Key)"
  file:
    path: '{{ sslpath }}'
    state: directory
    owner: fog
    group: apache
    mode: 0777 # This seems wrong from the script TODO: Check/Fix

- name: "Creating SSL Private Key"
  shell:
    openssl genrsa -out '{{ sslprivkey }}' 4096 

  #openssl_privatekey:
  #  path: '{{ sslprivkey }}'
  #  force: yes

- name: "Create SSL FOG CSR file"
  shell: 
    cmd: |
      openssl req -new -sha512 -key '{{ sslprivkey }}' -out '{{ vars["sslpath"] + "fog.csr" }}' << EOF
      .
      .
      .
      .
      .
      '{{ ipaddress }}'
      .


      EOF
#  openssl_csr:
#    path: '{{ vars["sslpath"] + "fog.csr" }}'
#    privatekey_path: '{{ sslprivkey }}'
#    country_name: US
#    organization_name: LTI
#    common_name: '{{ ipaddress }}'
#    email_address: tpostma@lssu.edu
#    force: True
# Below are shell scripts because I don't want to install an additional program
    
- name: "Creating SSL Certificate Directory"
  file:
    path: '{{ webdirdest }}management/other/ssl'
    state: directory
    owner: apache
    group: apache
    mode: 0777 # This seems wrong from the script TODO: Check/Fix

- name: "Create SSL Certificate for webdirdest/management/other/ssl (Creating SSL Certificate)" # This will probably break
  shell:
    openssl x509 -req -in '{{ vars["sslpath"] + "fog.csr" }}' -CA '{{ vars["sslpath"] + "CA/.fogCA.pem" }}' -CAkey '{{ vars["sslpath"] + "CA/.fogCA.key" }}' -CAcreateserial -out '{{ vars["docroot"] + "fog/" + "management/other/ssl/srvpublic.crt" }}' -days 3650
  #openssl_certificate:
  #  path: '{{ vars["webdirdest"] + "management/other/ssl/srvpublic.crt" }}'
  #  privatekey_path: '{{ vars["sslpath"] + "CA/.fogCA.key" }}'
  #  csr_path: '{{ vars["sslpath"] + "fog.csr" }}'
  #  provider: selfsigned
  #  force: True

- name: "Copy management/other/fogCA.pem"
  copy:
    src: '{{ sslpath }}CA/.fogCA.pem'
    dest: '{{ webdirdest }}management/other/ca.cert.pem'
    remote_src: yes

- name: "Generate public keys and auths"
  shell: 
    openssl x509 -outform der -in '{{ vars["docroot"] + "fog/" + "management/other/ca.cert.pem" }}' -out '{{ vars["docroot"] + "fog/" + "management/other/ca.cert.der" }}' 2>&1
    
- name: "Fix permissions in webdir"
  shell:
    chown -R '{{ apacheuser }}':'{{ apacheuser }}' '{{ vars["docroot"] + "fog/" + "management/other" }}'
   
# END createSSLCA


- name: "Copy FOG Host file to etcdest" # I'll be amazed if this works
  template:
    src: httpd/fog.conf.j2
    dest: '{{ etcconf }}'
  with_items: 
    - { ipaddress: '{{ ipaddress }}', docroot: '{{ docroot }}', webdirdest: '{{ webdirdest }}' }   
  notify: "restart web services"

- name: "Changing permissions on apache log files"
  shell: 
    chmod +rx '{{ apachelogdir }}' '{{ apacheerrlog }}' '{{ apacheacclog }}'


# Create Symlink in webdir (WHY????)
- name: "Create Symlink to iteself (for some reason)"
  file:
    src: /var/www/html/fog
    dest: /var/www/html/fog/fog
    owner: apache
    group: apache
    state: link
    force: yes


- name: "Fix apache permissions"
  shell: chown -R '{{ apacheuser }}':'{{ apacheuser }}' '{{ webdirdest }}'

# END configureHttpd

# Skipping backupDB
# Skipping updateDB

# BEGIN configureStorage

- name: "Setting up storageLocation directory"
  file:
    path: '{{ storageLocation }}'
    state: directory
    owner: fog
    group: root
    mode: 0777 # This seems wrong :(

- name: "Touch .mntcheck if it doesn't exist"
  file:
    path: '{{ storageLocation }}/.mntcheck'
    state: touch
    owner: fog
    group: root
    mode: 0777

- name: "Create postdownloadscripts under storageLocation"
  file:
    path: '{{ storageLocation }}/postdownloadscripts'
    state: directory
    owner: fog
    group: root
    mode: 0777 # This seems wrong :(
     
- name: "Configure fog.postdownload" # I'll be amazed if this works
  template:
    src: storageLocation/fog.postdownload.j2
    dest: '{{ storageLocation }}/postdownloadscripts/fog.postdownload'

- name: "Create storageLocationCapture directory"
  file:
    path: '{{ storageLocationCapture }}'
    state: directory
    owner: fog
    group: root
    mode: 0777 # This seems wrong :

- name: "Touch .mntcheck if it doesn't exist under storageLocationCapture"
  file:
    path: '{{ storageLocationCapture }}/.mntcheck'
    state: touch
    owner: fog
    group: root
    mode: 0777

- name: "Create postinitscripts under storageLocationCapture"
  file:
    path: '{{ storageLocationCapture }}/postinitscripts'
    state: directory
    owner: fog
    group: root
    mode: 0777 # This seems wrong :(

- name: "Configure fog.postinit" # I'll be amazed if this works
  template:
    src: storageLocation/fog.postinit.j2
    dest: '{{ storageLocationCapture }}/postinitscripts/fog.postinit'

- name: "Fix storageLocation Permissions"  
  shell: 
    chmod -R 777 '{{ storageLocation }}' '{{ storageLocationCapture }}'

- name: "Change storageLocation ownership"
  shell:
    chown -R '{{ username }}' '{{ storageLocation }}' '{{ storageLocationCapture }}'

# FINISH configureStorage

# skipping configureDHCP

# BEGIN configureTFTPandPXE

- name: "Create tftpdirdst directory"
  file:
    path: '{{ tftpdirdst }}'
    state: directory
    owner: fog
    group: root
    mode: 0751   

- name: "Remove tftpdirdst.prev"
  file:
    path: '{{ tftpdirdst }}.prev'
    state: absent

- name: "Create tftpdirdst.prev"
  file:
    path: '{{ tftpdirdst }}.prev'
    state: directory
    owner: root
    group: root
    mode: 0751   

- name: "Remove tftpdirdst.fogbackup (if it exists)"
  file:
    path: '{{ tftpdirdst }}.fogbackup'
    state: absent

- name: "Backup files from tftpdirdst to tftpdirdst.prev"
  shell: 
    cp -Rf /tftpboot/. /tftpboot.prev/

- name: "Create directories from a different directory (and fix permissions)"
  shell: |
    cp -rp /root/fogproject/packages/tftp/. /tftpboot/.

    chown -R '{{ username }}' '{{ tftpdirdst }}' 
    chown -R '{{ username }}' '{{ webdirdest }}'service/ipxe 

    find '{{ tftpdirdst }}' -type d -exec chmod 755 {} \; 
    find '{{ webdirdest }}' -type d -exec chmod 755 {} \; 
    find '{{ tftpdirdst }}' ! -type d -exec chmod 655 {} \; 

# configureDefaultiPXEfile

- name: "Copy default.ipxe to server"
  template:
    src: tftpboot/default.ipxe.j2
    dest: '{{ tftpdirdst }}/default.ipxe'
  with_items: 
    - { ipaddress: '{{ ipaddress }}' }   


- name: "Create backup for tftpconfig"
  shell: |
    if [[ -f '{{ item.tftpconfig }}' ]]; then
      cp -Rf '{{ item.tftpconfig }}' '{{ item.tftpconfig }}'.fogbackup 
    fi
  with_items:
    - { tftpconfig: '{{ tftpconfig }}' }  

- name: "Copy tftp server config to tftpconfig"
  template:
    src: tftpboot/tftp.j2
    dest: '{{ tftpconfig }}'

- name: "Enable and restart xinetd"
  systemd:
    name: xinetd
    state: restarted
    enabled: yes
# END configureTFTPandPXE

# BEGIN configureFTP
- name: "Copy VSFTP Config" # Skipping the backup portion though...
  template:
    src: vsftpd/vsftpd.conf.j2
    dest: '{{ ftpconfig }}'

- name: "Enable and restart VSFTPD"
  systemd:
    name: vsftpd
    state: restarted
    enabled: yes

# END configureFTP

# BEGIN configureSnapins
- name: "Setting up FOG Snapins"
  file:
    path: '{{ snapindir }}'
    state: directory
    owner: '{{ username }}'
    group: '{{ apacheuser }}'
    mode: 0777 # This seems wrong :(
# END configureSnapins

# BEGIN configureUDPCast
- name: "Setting up UDPCast" # TODO: I WILL NEED TO FIX THE PATHS ON THIS
  shell: |
    udpcastsrc="'{{ fogprojectdir }}'/packages/udpcast-20120424.tar.gz"
    udpcasttmp="/tmp/udpcast.tar.gz"

    cp -Rf "$udpcastsrc" "$udpcasttmp"
    cur=$(pwd)
    cd /tmp
    tar xvzf "$udpcasttmp" 
    cd $udpcastout
  
    dots "Configuring UDPCast"
    ./configure 
  
    dots "Building UDPCast"
    make 
  
    make install 
  
    cd $cur

# END configureUDPCast

# BEGIN installInitScript
- name: "Installing FOG System Scripts"
  shell: cp -f '{{ fogprojectdir }}/{{ initdsrc }}'/* '{{ initdpath }}'/ 

- name: "Reload system daemons"
  systemd: daemon_reload=yes
  
- name: "Change Permissions for Services"
  file:
    path: '{{ initdpath + "/" + item.servicename }}'
    owner: root
    group: root
    mode: 0644
  with_items: 
    - { servicename: '{{ initdMCfullname }}'}
    - { servicename: '{{ initdIRfullname }}'}
    - { servicename: '{{ initdSDfullname }}'}
    - { servicename: '{{ initdSRfullname }}'}
    - { servicename: '{{ initdSHfullname }}'}
    - { servicename: '{{ initdPHfullname }}'}
    - { servicename: '{{ initdISfullname }}'}

- name: "Enable FOG Services"
  systemd:
    name: '{{ item }}'
    state: stopped
    enabled: yes
  with_items: 
    - '{{ initdMCfullname }}'
    - '{{ initdIRfullname }}'
    - '{{ initdSDfullname }}'
    - '{{ initdSRfullname }}'
    - '{{ initdSHfullname }}'
    - '{{ initdPHfullname }}'
    - '{{ initdISfullname }}'

# END installInitScript

# BEGIN installFOGServices

- name: "Create FOG Service Directory"
  file:
    path: '{{ servicedst }}'
    state: directory
    owner: root
    group: root
    mode: 0771   

- name: "Copy FOG Services from packages to system location"
  shell: 
    cp -Rf /root/fogproject/packages/service/. '{{ servicedst + "/" }}'

- name: "Fix FOG Service Permissions"
  shell:
    chmod +x -R '{{ servicedst }}'/

- name: "Create Service log Directory"
  file:
    path: '{{ servicelogs }}'
    state: directory
    owner: root
    group: root
    mode: 0755  

# END installFOGServices

# BEGIN configureFOGService

- name: "Create FOG Service Etc Directory"
  file:
    path: '{{ servicedst }}/etc'
    state: directory
    owner: root
    group: root
    mode: 0771   

- name: "Configure config.php" # I'll be amazed if this works
  template:
    src: fogServices/config.php.j2
    dest: '{{ servicedst }}/etc/config.php'
  with_items: 
    - { webdirdest: '{{ webdirdest }}' }   

- name: "Restart FOG Services"
  systemd:
    name: '{{ item.servicename }}'
    state: restarted
    enabled: yes
  with_items: 
    - { servicename: '{{ initdMCfullname }}'}
    - { servicename: '{{ initdIRfullname }}'}
    - { servicename: '{{ initdSDfullname }}'}
    - { servicename: '{{ initdSRfullname }}'}
    - { servicename: '{{ initdSHfullname }}'}
    - { servicename: '{{ initdPHfullname }}'}
    - { servicename: '{{ initdISfullname }}'}

# END configureFOGService

# BEGIN configureNFS

- name: "Setting up exports file"
  template:
    src: nfs/exports.j2
    dest: '{{ nfsconfig }}'
  with_items: 
    - { storageLocation: '{{ storageLocation }}' }   

- name: "Setting up and starting RPCBind"
  systemd:
    name: rpcbind.service
    state: restarted
    enabled: yes

- name: "Setting up and starting NFS Server..."  
  systemd:
    name: '{{ item.servicename }}'
    state: restarted
    enabled: yes
  with_items: 
    - { servicename: 'nfs-server'}
    - { servicename: 'nfs'}
   # - { servicename: 'nfs-kernel-server'}
   
           
# END configureNFS

# BEGIN writeUpdateFile

- name: "Setting up fogsettings file" # I can add more variables to this file in the future if necessary
  template:
    src: fogsettings/fogsettings.j2
    dest: '{{ fogprogramdir }}/.fogsettings'
  with_items: 
    - { version: '{{ version }}', ipaddress: '{{ ipaddress }}', interface: '{{ interface }}', subnet: '{{ subnet }}', username: '{{ username }}', password: '{{ password }}' } 

# END writeUpdateFile

# BEGIN linkOptFogDir

- name: "Linking FOG Logs to Linux Logs"
  file:
    src: /opt/fog/log
    dest: /var/log/fog
    owner: root
    group: root
    state: link
    
- name: "Linking FOG Service Config to Linux Config (/etc)"
  file:
    src: /opt/fog/service/etc
    dest: /etc/fog
    owner: root
    group: root
    state: link
       
- name: "Fix Permissions to httpd and php logs"
  shell: |
    chmod -R 755 /var/log/httpd 
    for i in $(find /var/log/ -type d -name 'php*fpm*'); do
        chmod -R 755 $i 
    done
    for i in $(find /var/log/ -type f -name 'php*fpm*'); do
        chmod -R 755 $i 
    done

# END linkOptFogDir


# BEGIN updateStorageNodeCredentials

- name: "Ensuring node username and passwords match"
  shell: | 
    wget --no-check-certificate -qO - http://'{{ ipaddress + webroot + "maintenance/create_update_node.php" }}' --post-data="nodePass&ip=$(echo -n '{{ ipaddress }}'|base64)&user=$(echo -n '{{ username }}'|base64)&pass=$(echo -n "password"|base64)&fogverified"

# END updateStorageNodeCredentials

# BEGIN Print Final Message

- name: FOG Installation Complete!
  debug:
    msg:
      - '* Setup complete'
      - '- You can now login to the FOG Management Portal using'
      - '- the information listed below.  The login information'
      - '- is only if this is the first install.'
      - '- This can be done by opening a web browser and going to: '
      - '- http://{{ ipaddress }}{{ webroot }}management' 
      - '- Default User Information' 
      - '- Username: fog'     
      - '- Password: password'      

# END Print Final Message

# TIME FOR DEBUGGING!